### PR TITLE
Fix cache connection and invalidation in PATCH and DELETE routes

### LINKED ISSUE #67: Add cache system using Redis
https://github.com/chenyahui/gin-cache#cache-in-redis

### PR DESCRIPTION
**Pull request by Brawdunoir**

### CODE REVIEW

**Review by WhiteDiamondz — DISMISSED** [review]

File: routes/router.go [hunk 1]
```diff
@@ -136,7 +136,8 @@ func options(c *gin.Context) {
 
 func invalidateCacheURI(c *gin.Context) {
 	c.Next()
-	if redisStore != nil {
```
Comment (WhiteDiamondz) [inline routes/router.go]: Nope

**Review by WhiteDiamondz — CHANGES_REQUESTED** [review]

**Review by WhiteDiamondz — APPROVED** [review]
Good to go
